name: Build

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
