name: Build

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Test
        run: echo "${{ github.event }}"
